### PR TITLE
CPG Visualization

### PR DESCRIPTION
**Pull request by KeeyanGhoreshi**
For now, I'm importing the cpg file to test out the visualization of it.  I'm not sure how some of the resources are meant to connect to each other since I can't seem to generate a file with them included.  Like RequestGroup, for example.  Otherwise, all I need to do is repeat the process shown in the code for the other resources, extracting the `toState` value from wherever they hold their references to other CPG resources.

Visit `/demo/viz` to see the visualization.

### CODE REVIEW

**Review by blangley28 — COMMENTED** [review]
Was able to render a CPG file. A few comments:
- The graph is extremely small. It would be nice if it fit the entire screen so I don't need to zoom my browser 200% just to read it
- Are you planning on adding support for CarePlans too. While our CPG pathways do not have RequestGroups the resulting CarePlans do
- I forget how hard it is to do onclick action in graphviz but it would near if you could click on a node and it would open the resource
- I think it should show the actions as well as the ActivityDefinitions. There's a lot of information encoded in the actions which you don't see from the ActivityDefinitions (such as relatedActions and applicability conditions.

**Comment by KeeyanGhoreshi** [comment]
Testing for careplan done with this resource: 
`{
  "resourceType": "CarePlan",
  "contained": [ {
    "resourceType": "MedicationRequest",
    "id": "fffbe713-0073-4299-a996-cee0905a986e",
    "intent": "order",
    "medicationCodeableConcept": {
      "coding": [ {
        "system": "http://www.nlm.nih.gov/research/umls/rxnorm",
        "code": "1922509",
        "display": "trastuzumab"
      } ],
      "text": "trastuzumab"
    },
    "subject": {
      "reference": "Patient/example"
    }
  }, {
    "resourceType": "MedicationRequest",
    "id": "9bdaa0e1-78f8-454c-bd80-4c9b7bfa8c0b",
    "intent": "order",
    "medicationCodeableConcept": {
      "coding": [ {
        "system": "http://www.nlm.nih.gov/research/umls/rxnorm",
        "code": "1922509",
        "display": "trastuzumab"
      } ],
      "text": "trastuzumab"
    },
    "subject": {
      "reference": "Patient/example"
    }
  }, {
    "resourceType": "MedicationRequest",
    "id": "3cbd747a-a798-422f-93e1-a3b9b01d71fa",
    "intent": "order",
    "medicationCodeableConcept": {
      "coding": [ {
        "system": "http://www.nlm.nih.gov/research/umls/rxnorm",
        "code": "1922509",
        "display": "trastuzumab"
      } ],
      "text": "trastuzumab"
    },
    "subject": {
      "reference": "Patient/example"
    }
  }, {
    "resourceType": "RequestGroup",
    "id": "6540f0c4-55e5-4011-8f68-6e15268ddfc1",
    "status": "draft",
    "intent": "proposal",
    "action": [ {
      "relatedAction": [ {
        "actionId": "ChemotherapyTCHAC+TH",
        "relationship": "after-end"
      }, {
        "actionId": "-aRb-wkFPr",
        "relationship": "before-start"
      } ],
      "resource": {
        "reference": "#fffbe713-0073-4299-a996-cee0905a986e"
      }
    }, {
      "relatedAction": [ {
        "actionId": "LQ8xNgyRt",
        "relationship": "after-end"
      }, {
        "actionId": "R7nJd9OOYX",
        "relationship": "before-start"
      } ],
      "resource": {
        "reference": "#9bdaa0e1-78f8-454c-bd80-4c9b7bfa8c0b"
      }
    }, {
      "relatedAction": [ {
        "actionId": "ChemotherapyTHWeekly",
        "relationship": "after-end"
      }, {
        "actionId": "EndocrineTherapy",
        "relationship": "before-start"
      } ],
      "resource": {
        "reference": "#3cbd747a-a798-422f-93e1-a3b9b01d71fa"
      }
    } ]
  }, {
    "resourceType": "CarePlan",
    "id": "65037caf-dc52-4b74-8394-0bdcd141c54b",
    "instantiatesCanonical": [ "90e08eef-33b1-45cc-9842-80f959e4f50e" ],
    "status": "draft",
    "subject": {
      "reference": "Patient/example"
    },
    "activity": [ {
      "reference": {
        "reference": "#6540f0c4-55e5-4011-8f68-6e15268ddfc1"
      }
    } ]
  }, {
    "resourceType": "RequestGroup",
    "id": "d86965df-57f7-4eda-9005-ae99cd103926",
    "status": "draft",
    "intent": "proposal",
    "action": [ {
      "resource": {
        "reference": "#65037caf-dc52-4b74-8394-0bdcd141c54b"
      }
    } ]
  } ],
  "instantiatesCanonical": [ "4a208bf5-b534-4926-82e7-32d2a81c6b85", "90e08eef-33b1-45cc-9842-80f959e4f50e" ],
  "status": "draft",
  "subject": {
    "reference": "Patient/example"
  },
  "activity": [ {
    "reference": {
      "reference": "#d86965df-57f7-4eda-9005-ae99cd103926"
    }
  } ]
}`

**Comment by dehall** [comment]
@KeeyanGhoreshi Not sure what happened in the rebase but I can't seem to get to the viz page anymore.
Some thoughts on Ben's suggestions:
 - I agree the original graph was tiny, that should be larger by default
 - CarePlans should be in now
 - onClick would be really nice but probably not worth the time at this stage
 - I think we should show all the content and not just the IDs. I think the easiest way to do that for now is just stringify&pretty-print the entire resource and put that into the graph. Apologies if that was done already and I just don't see it

**Comment by KeeyanGhoreshi** [comment]
The graph is bigger now and zoomable, but showing all the content looks pretty difficult to read.  Besides being huge, the JSON can't really be displayed correctly because of some unknown rules restricting the content of the label of the node. 
 I had to remove all `{`, `}` and `"` and stringify it twice to escape the other special characters to get it to function.  Adding onClick() effects also appears to be quite a bit more work based on what I've read.  

image

**Comment by dehall** [comment]
Yeah `{ }` are special characters in DOT syntax so they would have to be escaped. Possibly others too.
Then the base64'ed library CQL is going to be a mess too... Not sure what to do about that.

I don't want to spend too much more time on this so just one more suggestion, instead of JSON might a YML view of the resource look better? https://github.com/nodeca/js-yaml

**Comment by KeeyanGhoreshi** [comment]
I think that one super-wide node is the one with base64 CQL data.  

YML might look better, but it probably won't solve the issue that the resources are super big and won't align correctly because the label doesn't support leading whitespace

**Review by dehall — APPROVED** [review]
Looks good. I think we could spend a lot of time to make it fancier, but this gets to the core of what I was looking for - a quick way to show the resources and references between them. If and when we return to CPG world then we can revisit to see if more detail would be necessary

**Review by blangley28 — APPROVED** [review]
LGTM

**Pull request merged**
